from . import purchase_receipt
from . import sales_order
from . import mrp_bom
from . import stock_picking
from . import stock_move
from . import stock_statement_report
from . import res_partner
from . import account_move
from . import product_template
from . import maintenance
from . import cold_storage
